---
abstract: 'release tests for your changelog'
author:
  - 'Mike Doherty <doherty@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-Test-CPAN-Changes
requires:
  Dist::Zilla::Plugin::InlineFiles: 0
  Dist::Zilla::Role::FileMunger: 0
  Moose: 0
  perl: 5.006
resources:
  bugtracker: http://github.com/doherty/Dist-Zilla-Plugin-Test-CPAN-Changes/issues
  repository: git://github.com/doherty/Dist-Zilla-Plugin-ChangesTests.git
version: 0.002
