---
abstract: 'release tests for your changelog'
author:
  - 'Mike Doherty <doherty@cpan.org>'
build_requires:
  File::Find: 0
  File::Path: 0
  File::Temp: 0
  Module::Build: 0.3601
  Moose::Autobox: 0
  Test::CPAN::Changes: 0
  Test::DZil: 0
  Test::More: 0.94
  autodie: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300032, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-Test-CPAN-Changes
no_index:
  directory:
    - corpus
    - inc
    - examples
requires:
  Data::Section: 0
  Dist::Zilla: 4
  Dist::Zilla::File::InMemory: 0
  Dist::Zilla::Role::FileGatherer: 0
  Dist::Zilla::Role::PrereqSource: 0
  Moose: 0
  Test::CPAN::Changes: 0.19
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/doherty/Dist-Zilla-Plugin-Test-CPAN-Changes/issues
  homepage: http://metacpan.org/release/Dist-Zilla-Plugin-Test-CPAN-Changes/
  repository: git://github.com/doherty/Dist-Zilla-Plugin-Test-CPAN-Changes.git
version: 0.008
